Repository imagej/napari-imagej, pull requests merged in 2023-05, with the labels that each got.

#190 Bump ImageJ Legacy version
  src/napari_imagej/java.py
Labels: bug, blocked

#167 Add support for boolean-type image conversion
  dev-environment.yml
  environment.yml
  pyproject.toml
  src/napari_imagej/java.py
  tests/types/test_converters.py
  tests/widgets/test_result_runner.py
Labels: enhancement

#187 Bump scijava search version
  src/napari_imagej/java.py
  tests/widgets/test_result_runner.py
Labels: enhancement, blocked

#207 Redirect legacy commands to the ImageJ UI
  src/napari_imagej/java.py
  src/napari_imagej/widgets/menu.py
  src/napari_imagej/widgets/result_runner.py
  src/napari_imagej/widgets/result_tree.py
  src/napari_imagej/widgets/widget_utils.py
  tests/utils.py
  tests/widgets/test_menu.py
Labels: enhancement

#219 Capture and handle moduleerroredevent
  bin/test.sh
  src/napari_imagej/java.py
  src/napari_imagej/utilities/events.py
  src/napari_imagej/utilities/logging.py
  src/napari_imagej/utilities/progress_manager.py
  src/napari_imagej/widgets/menu.py
  src/napari_imagej/widgets/napari_imagej.py
  tests/utilities/test_progress.py
  tests/utils.py
  tests/widgets/test_menu.py
  tests/widgets/test_napari_imagej.py
Labels: bug, enhancement

#225 Include necessary resources
  MANIFEST.in
Labels: bug

#229 Finish removing Qt from java.py
  src/napari_imagej/java.py
  src/napari_imagej/utilities/event_subscribers.py
  src/napari_imagej/widgets/menu.py
  src/napari_imagej/widgets/napari_imagej.py
  src/napari_imagej/widgets/searchbar.py
  tests/conftest.py
  tests/widgets/test_menu.py
  tests/widgets/test_napari_imagej.py
Labels: bug, enhancement

#230 Misc pre release changes
  scripts/Plugins/Examples/Widget_Demo.js
  src/napari_imagej/napari.yml
Labels: enhancement

#228 Write installation instructions for production pathways
  doc/Benchmarking.rst
  doc/Configuration.rst
  doc/Install.rst
  doc/examples/scripting.rst
  src/napari_imagej/widgets/menu.py
Labels: documentation, blocked

#235 Improve settings dialog labels
  doc/Benchmarking.rst
  doc/Configuration.rst
  doc/Development.rst
  doc/examples/scripting.rst
  src/napari_imagej/widgets/menu.py
  tests/widgets/test_menu.py
Labels: documentation

#247 Fix Pyproject.toml links
  pyproject.toml
Labels: bug

#249 Ensure that Python exceptions during initialization are also printed
  src/napari_imagej/widgets/napari_imagej.py
  tests/widgets/test_napari_imagej.py
Labels: bug

#251 confuse: avoid reading in constructor
  src/napari_imagej/settings.py
Labels: bug
